# Site settings
title: "sadeceben"
bye_message: "I am a hacker, and this is my manifesto.  You may stop this individual,
                    but you can't stop us all... after all, we're all alike.

                                         +++The Mentor+++"
baseurl: "https://sadeceben.github.io/"
url: "https://sadeceben.github.io"
disqus: sadeceben

# Header settings
nick: "sadeceben"
mail:
    domain: "sadeceben@vuhuv.com"
    ext: "com"
source_code:
    server: "github.com"
    nick: "sadeceben"
blog:
    server: "github.com"
    nick: "sadeceben"
#fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
