# Site settings
title: "Cemal Tiryaki"
bye_message: "Good Byyy Friends..."
baseurl: "/clyell/"
url: "sadeceben.github.io"
disqus: cemaltiryaki

# Header settings
nick: "sadeceben"
mail:
    domain: "cemaltiryaki01@gmail.com"
    ext: "ch"
source_code:
    server: "https://sadeceben.github.io"
    nick: "sadeceben"
blog:
    server: "https://sadeceben.github.io"
    nick: "sadeceben"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

theme: jekyll-theme-hacker
